### ISSUE TITLE
Weird issue with Ruby Enterprise Edition.

### ISSUE THREAD

**Issue by jimeh** [quirkey/jim#2]
I've got REE among other versions of Ruby installed with RVM. With REE however, `jim init` causing the follow error:

```
/Users/jim/.rvm/gems/ree-1.8.7-2010.01/gems/jim-0.1.0/lib/jim/cli.rb:121:in `parse_options': uninitialized constant Jim::CLI::OptionParser (NameError)
    from /Users/jim/.rvm/gems/ree-1.8.7-2010.01/gems/jim-0.1.0/lib/jim/cli.rb:12:in `initialize'
    from /Users/jim/.rvm/gems/ree-1.8.7-2010.01/gems/jim-0.1.0/bin/jim:5:in `new'
    from /Users/jim/.rvm/gems/ree-1.8.7-2010.01/gems/jim-0.1.0/bin/jim:5
    from /Users/jim/.rvm/gems/ree-1.8.7-2010.01/bin/jim:19:in `load'
    from /Users/jim/.rvm/gems/ree-1.8.7-2010.01/bin/jim:19
```

**Comment by quirkey** [comment]
I think this was because I didnt expicitly require optparse.rb. I pushed a new version last night - can you test and let me know if it fixes it? The test suite passes on REE with RVM right now.

**Comment by jimeh** [comment]
Yepp, 0.1.1 works fine now :)
